### ISSUE TITLE
Help getting morphdom to work with marko-vdom on the server. Please?

### ISSUE THREAD

**Issue by willfind** [marko-js/marko-vdom#2]
We've been trying to get morphdom working with a marko-vdom virtual dom object on the server side, but unfortunately all of our many attempts have failed. Our goal is to get a diffing dom working successfully on the server side.

It seems that morphdom is always looking for a global document object. For instance, line 6 of morphdom.js:

var doc = typeof document === 'undefined' ? undefined : document;

But we can't figure out how to make marko-vdom provide such a global document.

Does anyone have a working example of using morphdom successfully with mark-vdom on the server side? We'd really appreciate your help!

**Comment by patrick-steele-idem** [comment]
Responded over in the morphdom project: https://github.com/patrick-steele-idem/morphdom/issues/98

Closing this issue.
